### ISSUE TITLE
model dir missing!!!

### ISSUE THREAD

**Issue by focox** [twjiang/fact_triple_extraction#5]
where is MODELDIR="/data/ltp/ltp-models/3.3.0/ltp_data"

**Comment by twjiang** [comment]
From http://ltp.ai/download.html <http://ltp.ai/download.html> you can get the model file in this column:



And the pyltp can be installed by: pip install pyltp.

姜天文  Tianwen Jiang
社会计算与信息检索研究中心, 哈尔滨工业大学
Research Center for Social Computing and Information Retrieval, HIT
